name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      id-token: write # This is required for requesting the JWT
      #  contents: read  # This is required for actions/checkout
      actions: read
      deployments: write
      contents: write
      attestations: write # Not sure is this needed
    name: deploy dbt
    uses: SunrayAnalytics/data_platform/.github/workflows/deploy_dbt.yaml@main
    with:
      environment: prod
    secrets: inherit
